SELECT * FROM MOVIES;
SELECT FIRST_NAME, LAST_NAME, RATING 
FROM ACTORS;
SELECT TITLE
FROM SERIES;

SELECT FIRST_NAME, LAST_NAME
FROM ACTORS
WHERE RATING > 7.5;

SELECT TITLE, RATING, AWARDS
FROM MOVIES
WHERE RATING > 7.5 AND AWARDS >2;

SELECT TITLE, RATING 
FROM MOVIES 
ORDER BY RATING;

SELECT TITLE, RATING
FROM MOVIES
WHERE TITLE LIKE "TOY STORY%";

SELECT *
FROM ACTORS
WHERE FIRST_NAME LIKE "SAM%"

